/**
 * Expo Config Plugin: withLlamaRn
 *
 * llama.rn auto-links its native code via React Native autolinking, but
 * its native classes (`com.rnllama.*`) get stripped by R8/ProGuard in
 * release builds. The library README requires this keep rule to survive
 * minification:
 *
 *   -keep class com.rnllama.** { *; }
 *
 * `android/app/proguard-rules.pro` is regenerated by Expo prebuild on
 * every clean — direct edits don't survive. This plugin appends the
 * keep rule idempotently inside marker comments so re-running prebuild
 * is safe.
 *
 * Dev builds (`pnpm android`) don't run ProGuard, so this is purely a
 * release/EAS-build concern. Still, it must be in place before any
 * release build, and the right time to wire it is alongside the install.
 */

const { withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const PLUGIN_NAME = 'withLlamaRn';
const MARKER_BEGIN = '# withLlamaRn — BEGIN';
const MARKER_END = '# withLlamaRn — END';
const KEEP_RULE = '-keep class com.rnllama.** { *; }';

const withLlamaRnProguard = (config) =>
  withDangerousMod(config, [
    'android',
    async (modConfig) => {
      const platformRoot = modConfig.modRequest.platformProjectRoot;
      const proguardFile = path.join(platformRoot, 'app', 'proguard-rules.pro');

      let contents = '';
      if (fs.existsSync(proguardFile)) {
        contents = fs.readFileSync(proguardFile, 'utf8');
      }

      if (contents.includes(MARKER_BEGIN)) {
        // Idempotent — already injected. Skip.
        return modConfig;
      }

      const block = `\n${MARKER_BEGIN}\n${KEEP_RULE}\n${MARKER_END}\n`;
      const next = (contents.endsWith('\n') ? contents : contents + '\n') + block;
      fs.writeFileSync(proguardFile, next);
      console.log(`[${PLUGIN_NAME}] appended llama.rn keep rule → ${proguardFile}`);
      return modConfig;
    },
  ]);

module.exports = withLlamaRnProguard;
