/**
 * On-device inference service.
 *
 * Real implementation backed by `llama.rn`. Loads Antoine's GGUF model
 * file, builds the message array with the system prompt, runs completion
 * on-device, and streams tokens to an optional callback.
 *
 * Public API surface is preserved from the prior stub so callers
 * (`useAntoine`) only change to pass a real path and a streaming callback.
 *
 * Privacy invariant (CLAUDE.md, wiki/concepts/privacy-invariant.md):
 *   This file makes ZERO remote requests. The model is loaded from local
 *   disk; tokens are generated by `llama.rn` running natively. No remote
 *   transport of any kind is permitted here.
 *   CI verifies this — see wiki/concepts/privacy-invariant.md for the
 *   exact grep used in code review. It must return zero matches against
 *   this file.
 */
import {
  addNativeLogListener,
  initLlama as nativeInitLlama,
  type LlamaContext as NativeLlamaContext,
  releaseAllLlama as nativeReleaseAll,
  toggleNativeLog,
  type TokenData,
} from 'llama.rn';

import { ANTOINE_SYSTEM_PROMPT } from '@/constants/antoine';
import type { InferenceMessage, InferenceResult } from '@/types/inference';

// Surface llama.cpp's native stderr (model load failures, gguf format
// errors, mmap/OOM messages) to the JS side once at module load. Without
// this, llama.rn swallows the underlying reason and you only see the
// generic "unable to load model" wrapper message in logcat. Routed
// through console.warn so it shows up in `adb logcat ReactNativeJS:V`.
let nativeLogEnabled = false;
function enableNativeLogOnce(): void {
  if (nativeLogEnabled) return;
  nativeLogEnabled = true;
  void toggleNativeLog(true).catch(() => undefined);
  addNativeLogListener((level, text) => {
    console.warn(`[llama.rn:${level}] ${text}`);
  });
}

/**
 * Wrapper around llama.rn's native context. We keep our own opaque shape
 * (`{ id, modelPath, native }`) so callers don't depend on llama.rn's
 * internal class. `native` is the underlying LlamaContext used to call
 * completion / release.
 */
export interface LlamaContext {
  id: number;
  modelPath: string;
  native: NativeLlamaContext;
}

export interface InitOptions {
  /** Absolute path to the main GGUF file on device. */
  model: string;
  /** Reserved for multimodal — unused this milestone. */
  mmproj?: string;
  /**
   * KV cache size in tokens. Default 1024 — chosen to fit alongside the
   * Antoine gemma4 model on an 8 GB phone. Empirically, n_ctx=2048 with
   * the model's ~2.8 GB of CPU_REPACK buffers + JS runtime + Android
   * system OOM-killed the app during prefill on the Moto G86 Power.
   */
  contextSize?: number;
  /**
   * Prefill batch size in tokens. Default 256. llama.cpp's default of 2048
   * allocates a compute buffer sized for a 2048-token prefill at once,
   * which is excessive when our prompts are small and memory is tight.
   * Smaller n_batch trades a little prefill speed for lower peak memory.
   */
  batchSize?: number;
  /** CPU thread count for inference. Default 4. */
  threadCount?: number;
}

export interface CompletionParams {
  messages: InferenceMessage[];
}

export type TokenCallback = (token: string) => void;

/**
 * Test-only switch. Set `__forceError.value = true` to make initLlama or
 * completion throw, exercising the chat error path without needing the
 * real model.
 */
export const __forceError = { value: false };

/** Stop tokens for Gemma chat template + a safety net for other tags. */
const STOP_TOKENS = ['<end_of_turn>', '<|end_of_turn|>', '<eos>', '</s>', '<|endoftext|>'] as const;

const STOP_TOKEN_SET = new Set<string>(STOP_TOKENS);

export async function initLlama(options: InitOptions): Promise<LlamaContext> {
  if (__forceError.value) {
    throw new Error('Couldn’t load Antoine. Check the model files in Settings.');
  }
  enableNativeLogOnce();
  const native = await nativeInitLlama({
    model: options.model,
    // n_ctx=2048 is now safe with the Q4_0 main weights (NEON-native, no
    // repack buffer) + Q4_0 KV cache (~18 MB combined at this size).
    // The earlier 1536 ceiling was forced by Q4_K_M's CPU_REPACK buffer
    // colliding with the Android low-memory killer. With both weights
    // and KV at Q4_0 the device has headroom — verified empirically.
    n_ctx: options.contextSize ?? 2048,
    // 256 batch size. Tested 512 on 2026-04-30 — same prefill timing on
    // the Dimensity 7300 but +308 MiB compute buffer for nothing. Prefill
    // is matmul-bound on the A78 cores, not batch-overhead-bound, so
    // bigger batches don't help.
    n_batch: options.batchSize ?? 256,
    n_ubatch: options.batchSize ?? 256,
    n_threads: options.threadCount ?? 4,
    n_gpu_layers: 0,
    // No-op for Q4_0 weights (Q4_0 has no repack buffer to skip), but
    // kept as a defensive flag in case llama.cpp adds extra buffer types
    // in a future bump that would re-trigger the OOM. Originally added
    // for Q4_K_M weights where the SIMD repack added ~2.8 GB heap on
    // top of the 5 GB mmap'd weights and OOM-killed the app.
    no_extra_bufts: true,
    // KV cache stored as Q4_0. At n_ctx=2048 this is ~18 MB combined K+V.
    // Tested Q8_0 on 2026-04-30 — app SIGKILL'd by Android's low-memory
    // killer (~+18 MB pushed past the ceiling). flash-attention runs
    // fine with Q4_0 KV in this build of llama.rn (verified empirically
    // — log showed `Flash Attention was auto, set to enabled` with Q4_0).
    // Off-grid's claim that Q4_0+flash-attn isn't supported was wrong
    // for our specific binary.
    cache_type_k: 'q4_0',
    cache_type_v: 'q4_0',
    // Flash-attention is on by default at flash_attn=auto in llama.rn
    // 0.12.0-rc.5; explicit `flash_attn_type: 'auto'` was tested and
    // contributed to the OOM combined with Q8_0 KV. Removed to stay at
    // the implicit default which IS active (verified in logcat).
  });
  return { id: native.id, modelPath: options.model, native };
}

export async function completion(
  ctx: LlamaContext,
  params: CompletionParams,
  onToken?: TokenCallback,
): Promise<InferenceResult> {
  if (__forceError.value) {
    throw new Error('Antoine stalled. Try the question again.');
  }
  const result = await ctx.native.completion(
    {
      messages: params.messages,
      // n_ctx is 1536. n_predict eats from the same budget as input. On
      // the first RAG turn (system + 2 chunks + user), input is ~700
      // tokens; n_predict=384 leaves headroom and still produces a
      // 150-200 word answer — plenty for a culinary reply.
      n_predict: 384,
      temperature: 0.7,
      top_p: 0.9,
      stop: [...STOP_TOKENS],
      // Disable Gemma's <|channel|>thought reasoning block. The kwarg is
      // typed as Record<string, string> and rendered through Jinja —
      // where ANY non-empty string is truthy, so the literal "false"
      // counts as truthy and would leave thinking enabled. Empty string
      // is the falsy value Jinja respects. (Confirmed empirically: the
      // string "false" did not suppress the <|channel>thought block.)
      chat_template_kwargs: { enable_thinking: '' },
    },
    onToken
      ? (data: TokenData) => {
          const t = data.token ?? '';
          if (!t) return;
          if (STOP_TOKEN_SET.has(t)) return;
          onToken(t);
        }
      : undefined,
  );
  return { text: result.text ?? '', tokensUsed: result.timings?.predicted_n };
}

export async function releaseAllLlama(): Promise<void> {
  await nativeReleaseAll();
}

export function buildMessageArray(history: InferenceMessage[]): InferenceMessage[] {
  return [{ role: 'system', content: ANTOINE_SYSTEM_PROMPT }, ...history];
}
