/**
 * On-device inference service.
 *
 * Real implementation backed by `llama.rn`. Loads Antoine's GGUF model
 * file, builds the message array with the system prompt, runs completion
 * on-device, and streams tokens to an optional callback.
 *
 * Public API surface is preserved from the prior stub so callers
 * (`useAntoine`) only change to pass a real path and a streaming callback.
 *
 * Privacy invariant (CLAUDE.md, wiki/concepts/privacy-invariant.md):
 *   This file makes ZERO remote requests. The model is loaded from local
 *   disk; tokens are generated by `llama.rn` running natively. No remote
 *   transport of any kind is permitted here.
 *   CI verifies this — see wiki/concepts/privacy-invariant.md for the
 *   exact grep used in code review. It must return zero matches against
 *   this file.
 */
import {
  addNativeLogListener,
  initLlama as nativeInitLlama,
  type LlamaContext as NativeLlamaContext,
  releaseAllLlama as nativeReleaseAll,
  toggleNativeLog,
  type TokenData,
} from 'llama.rn';
import llamaRnPkg from 'llama.rn/package.json';

import * as FileSystem from 'expo-file-system/legacy';

import { ANTOINE_SYSTEM_PROMPT } from '@/constants/antoine';
import { getMainModelPath, getMmprojPath, toFileUri } from '@/services/modelLocator';
import type { InferenceMessage, InferenceResult } from '@/types/inference';

// Surface llama.cpp's native stderr (model load failures, gguf format
// errors, mmap/OOM messages) to the JS side once at module load. Without
// this, llama.rn swallows the underlying reason and you only see the
// generic "unable to load model" wrapper message in logcat. Routed
// through console.warn so it shows up in `adb logcat ReactNativeJS:V`.
let nativeLogEnabled = false;
function enableNativeLogOnce(): void {
  if (nativeLogEnabled) return;
  nativeLogEnabled = true;
  void toggleNativeLog(true).catch(() => undefined);
  addNativeLogListener((level, text) => {
    console.warn(`[llama.rn:${level}] ${text}`);
  });
}

/**
 * Wrapper around llama.rn's native context. We keep our own opaque shape
 * (`{ id, modelPath, native }`) so callers don't depend on llama.rn's
 * internal class. `native` is the underlying LlamaContext used to call
 * completion / release.
 */
export interface LlamaContext {
  id: number;
  modelPath: string;
  native: NativeLlamaContext;
  /**
   * True iff `initMultimodal` was called on this context AND succeeded.
   * Callers passing image attachments should check this and fall back to
   * text-only when false (otherwise the model receives no image bytes
   * and hallucinates content). See `useAntoine.send`.
   */
  multimodalEnabled: boolean;
}

/**
 * Single source of truth for the runtime parameters passed to
 * `initLlama`. Used inside this module AND read by `kvSessionService`
 * to detect "the runtime fingerprint changed since we saved this KV
 * state" — sidecar mismatch invalidates the saved state.
 *
 * Bump any value here only after empirical device verification on the
 * Moto G86 Power. See wiki/decisions/llama-rn-inference-params.md for
 * the reasoning behind each value.
 */
export const INFERENCE_RUNTIME = {
  n_ctx: 2048,
  n_batch: 256,
  n_threads: 4,
  cache_type_k: 'q4_0',
  cache_type_v: 'q4_0',
} as const;

/**
 * llama.rn's binary KV-cache format may change across releases. The
 * sidecar JSON next to each saved KV blob records the version that
 * wrote it; on load, a mismatch invalidates and we re-prefill once.
 */
export const LLAMA_RN_VERSION: string = llamaRnPkg.version;

export interface InitOptions {
  /** Absolute path to the main GGUF file on device. */
  model: string;
  /** Reserved for multimodal — unused this milestone. */
  mmproj?: string;
  /**
   * KV cache size in tokens. Default 1024 — chosen to fit alongside the
   * Antoine gemma4 model on an 8 GB phone. Empirically, n_ctx=2048 with
   * the model's ~2.8 GB of CPU_REPACK buffers + JS runtime + Android
   * system OOM-killed the app during prefill on the Moto G86 Power.
   */
  contextSize?: number;
  /**
   * Prefill batch size in tokens. Default 256. llama.cpp's default of 2048
   * allocates a compute buffer sized for a 2048-token prefill at once,
   * which is excessive when our prompts are small and memory is tight.
   * Smaller n_batch trades a little prefill speed for lower peak memory.
   */
  batchSize?: number;
  /** CPU thread count for inference. Default 4. */
  threadCount?: number;
}

export interface CompletionParams {
  messages: InferenceMessage[];
}

export type TokenCallback = (token: string) => void;

/**
 * Test-only switch. Set `__forceError.value = true` to make initLlama or
 * completion throw, exercising the chat error path without needing the
 * real model.
 */
export const __forceError = { value: false };

/** Stop tokens for Gemma chat template + a safety net for other tags. */
const STOP_TOKENS = ['<end_of_turn>', '<|end_of_turn|>', '<eos>', '</s>', '<|endoftext|>'] as const;

const STOP_TOKEN_SET = new Set<string>(STOP_TOKENS);

/**
 * Module-level turn counter for timing diagnostics. Increments on every
 * successful completion() call so log lines can be paired across turns
 * (turn 1 is full prefill; turn 2+ should show cache_n > 0 if llama.cpp's
 * internal prompt-cache reuses any prefix).
 */
let timingTurnCounter = 0;

/**
 * Best-effort multimodal initialization. Calls `native.initMultimodal`
 * with the mmproj projector path. Returns false (and logs a warning)
 * on any failure — caller should fall back to text-only inference.
 *
 * Why best-effort: the mmproj file is a separate ~1 GB download; on a
 * fresh install or after a settings reset it may not be on disk yet.
 * The chat path stays usable for text without it.
 */
async function tryInitMultimodal(native: NativeLlamaContext, mmprojPath: string): Promise<boolean> {
  try {
    const fileInfo = await FileSystem.getInfoAsync(toFileUri(mmprojPath));
    if (!fileInfo.exists) {
      console.warn(`[inferenceService] mmproj not on disk at ${mmprojPath} — vision disabled`);
      return false;
    }
    const ok = await native.initMultimodal({ path: mmprojPath, use_gpu: false });
    if (!ok) {
      console.warn('[inferenceService] initMultimodal returned false — mmproj load failed');
      return false;
    }
    const support = await native.getMultimodalSupport();
    console.info(
      `[inferenceService] multimodal initialized — vision=${support.vision} audio=${support.audio}`,
    );
    return support.vision;
  } catch (e) {
    console.warn('[inferenceService] tryInitMultimodal threw:', e);
    return false;
  }
}

export async function initLlama(options: InitOptions): Promise<LlamaContext> {
  if (__forceError.value) {
    throw new Error('Couldn’t load Antoine. Check the model files in Settings.');
  }
  enableNativeLogOnce();
  const native = await nativeInitLlama({
    model: options.model,
    // n_ctx=2048 is now safe with the Q4_0 main weights (NEON-native, no
    // repack buffer) + Q4_0 KV cache (~18 MB combined at this size).
    // The earlier 1536 ceiling was forced by Q4_K_M's CPU_REPACK buffer
    // colliding with the Android low-memory killer. With both weights
    // and KV at Q4_0 the device has headroom — verified empirically.
    n_ctx: options.contextSize ?? INFERENCE_RUNTIME.n_ctx,
    // 256 batch size. Tested 512 on 2026-04-30 — same prefill timing on
    // the Dimensity 7300 but +308 MiB compute buffer for nothing. Prefill
    // is matmul-bound on the A78 cores, not batch-overhead-bound, so
    // bigger batches don't help.
    n_batch: options.batchSize ?? INFERENCE_RUNTIME.n_batch,
    n_ubatch: options.batchSize ?? INFERENCE_RUNTIME.n_batch,
    n_threads: options.threadCount ?? INFERENCE_RUNTIME.n_threads,
    n_gpu_layers: 0,
    // No-op for Q4_0 weights (Q4_0 has no repack buffer to skip), but
    // kept as a defensive flag in case llama.cpp adds extra buffer types
    // in a future bump that would re-trigger the OOM. Originally added
    // for Q4_K_M weights where the SIMD repack added ~2.8 GB heap on
    // top of the 5 GB mmap'd weights and OOM-killed the app.
    no_extra_bufts: true,
    // KV cache stored as Q4_0. At n_ctx=2048 this is ~18 MB combined K+V.
    // Tested Q8_0 on 2026-04-30 — app SIGKILL'd by Android's low-memory
    // killer (~+18 MB pushed past the ceiling). flash-attention runs
    // fine with Q4_0 KV in this build of llama.rn (verified empirically
    // — log showed `Flash Attention was auto, set to enabled` with Q4_0).
    // Off-grid's claim that Q4_0+flash-attn isn't supported was wrong
    // for our specific binary.
    cache_type_k: INFERENCE_RUNTIME.cache_type_k,
    cache_type_v: INFERENCE_RUNTIME.cache_type_v,
    // Flash-attention is on by default at flash_attn=auto in llama.rn
    // 0.12.0-rc.5; explicit `flash_attn_type: 'auto'` was tested and
    // contributed to the OOM combined with Q8_0 KV. Removed to stay at
    // the implicit default which IS active (verified in logcat).
    // Tried `kv_unified: true` (off-grid recommendation) — silently
    // dropped before the native binding in 0.12.0-rc.5. Param was
    // added in a later llama.rn release.
  });
  // Wire the mmproj projector for vision input if the caller passed a
  // path. Best-effort — text-only inference works fine without it.
  const multimodalEnabled = options.mmproj
    ? await tryInitMultimodal(native, options.mmproj)
    : false;
  return { id: native.id, modelPath: options.model, native, multimodalEnabled };
}

/**
 * Module-level cached context. Loaded lazily by the first caller
 * (chat send or boot pre-warm) and reused across the JS lifetime.
 * Multi-second cold load on first use; near-instant after that.
 *
 * Both `useAntoine.send()` and the boot effect in `app/_layout.tsx`
 * call `ensureContext()` so the context is shared. The boot effect
 * pre-warms in the background while the user is reading the chat tab,
 * so the first send doesn't pay the cold load.
 */
let cachedContext: LlamaContext | null = null;

export async function ensureContext(): Promise<LlamaContext> {
  if (cachedContext) return cachedContext;
  const modelPath = await getMainModelPath();
  // Resolve the mmproj path — it may or may not be on disk; tryInitMultimodal
  // verifies existence and downgrades gracefully to text-only.
  const mmprojPath = await getMmprojPath().catch(() => undefined);
  cachedContext = await initLlama({ model: modelPath, mmproj: mmprojPath });
  return cachedContext;
}

export function getCachedContext(): LlamaContext | null {
  return cachedContext;
}

/**
 * Drops the cached context and releases the native llama.cpp resources.
 * Future settings UI (path-override) calls this when the user changes
 * the model directory; that caller is also responsible for clearing
 * any saved KV-state files via `kvSessionService.deleteSavedKV()` —
 * KV state saved against a now-released context is unsafe to restore.
 */
export async function releaseCachedContext(): Promise<void> {
  cachedContext = null;
  await nativeReleaseAll();
}

export async function completion(
  ctx: LlamaContext,
  params: CompletionParams,
  onToken?: TokenCallback,
): Promise<InferenceResult> {
  if (__forceError.value) {
    throw new Error('Antoine stalled. Try the question again.');
  }
  const result = await ctx.native.completion(
    {
      messages: params.messages,
      // n_ctx is 1536. n_predict eats from the same budget as input. On
      // the first RAG turn (system + 2 chunks + user), input is ~700
      // tokens; n_predict=384 leaves headroom and still produces a
      // 150-200 word answer — plenty for a culinary reply.
      n_predict: 384,
      temperature: 0.7,
      top_p: 0.9,
      stop: [...STOP_TOKENS],
      // Disable Gemma's <|channel|>thought reasoning block. The kwarg is
      // typed as Record<string, string> and rendered through Jinja —
      // where ANY non-empty string is truthy, so the literal "false"
      // counts as truthy and would leave thinking enabled. Empty string
      // is the falsy value Jinja respects. (Confirmed empirically: the
      // string "false" did not suppress the <|channel>thought block.)
      chat_template_kwargs: { enable_thinking: '' },
      // `reasoning_format` default is already 'none' in llama.rn 0.12.0-rc.5
      // (verified by reading node_modules/llama.rn/src/index.ts). Explicitly
      // set elsewhere in the off-grid repo for newer versions; no-op for us.
      // `ctx_shift` is not exposed in this version's TS surface — added in
      // a later release. Stuck with the default (re-prefill on overflow).
    },
    onToken
      ? (data: TokenData) => {
          const t = data.token ?? '';
          if (!t) return;
          if (STOP_TOKEN_SET.has(t)) return;
          onToken(t);
        }
      : undefined,
  );
  timingTurnCounter += 1;
  const t = result.timings;
  if (t) {
    console.info(
      `[inferenceService] turn=${timingTurnCounter} ` +
        `cache_n=${t.cache_n} ` +
        `prompt_n=${t.prompt_n} ` +
        `prompt_ms=${Math.round(t.prompt_ms)} ` +
        `prompt_per_second=${t.prompt_per_second?.toFixed?.(2) ?? t.prompt_per_second} ` +
        `predicted_n=${t.predicted_n} ` +
        `predicted_ms=${Math.round(t.predicted_ms)}`,
    );
  } else {
    console.info(
      `[inferenceService] turn=${timingTurnCounter} timings=null (native didn't return timings object)`,
    );
  }
  return { text: result.text ?? '', tokensUsed: result.timings?.predicted_n };
}

export async function releaseAllLlama(): Promise<void> {
  await nativeReleaseAll();
}

export function buildMessageArray(history: InferenceMessage[]): InferenceMessage[] {
  return [{ role: 'system', content: ANTOINE_SYSTEM_PROMPT }, ...history];
}
